"""Initial migration

Revision ID: 463316b62eaa
Revises: 7ef962b25d08
Create Date: 2024-08-26 14:00:05.335776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463316b62eaa'
down_revision: Union[str, None] = '7ef962b25d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'book_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('book_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
