"""Initial migration

Revision ID: 7ef962b25d08
Revises: 3519a941e9a7
Create Date: 2024-08-26 13:55:03.581817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef962b25d08'
down_revision: Union[str, None] = '3519a941e9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'authors', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_column('authors', 'book_id')
    # ### end Alembic commands ###
